project:
  type: website
  output-dir: .  # This will output the files to the root of the repository

website:
  title: "cenith"
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




